typography_spectrum: 0.9077215653378516
color:
  brandStrength: 0.3223353549838066
  lightness: 0.799409180181101
  saturation: 0.4141698812600225
  rhythmicContrast: 0.6926178461872041
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
layout_spectrum: 0.8131392488721758
name: 'Lyn Cruz '
navigation:
  - name: 'About me. '
    id: 482fb060-16fb-495c-8ebd-0fbd553fda16
    type: content
title: '` This & that . '
description: >-
  ` Fill your life with experiences, not things. Have stories to tell, not stuff
  to show. 
